SELECT MA_NVIEN, COUNT(*) AS SL
FROM PHANCONG
GROUP BY MA_NVIEN
HAVING COUNT(*) > 2

SELECT TOP 3 *
FROM NHANVIEN
ORDER BY LUONG DESC

SELECT NV.MANV, NV.TENNV
FROM NHANVIEN NV
WHERE NOT EXISTS (
					SELECT *
					FROM DEAN DA
					WHERE NOT EXISTS (
										SELECT *
										FROM PHANCONG PC
										WHERE PC.MADA = DA.MADA
										AND NV.MANV = PC.MA_NVIEN
										))

SELECT MANV, TENNV
FROM NHANVIEN, PHANCONG
WHERE MANV = MA_NVIEN
GROUP BY MANV, TENNV
HAVING COUNT(*) = (
					SELECT COUNT(*)
					FROM DEAN )

SELECT NV.MANV, NV.TENNV, PB.TENPHG
FROM NHANVIEN NV LEFT JOIN PHONGBAN PB ON NV.MANV = PB.TRPHG


SELECT DA.TENDA, PB.TENPHG, NV.TENNV, PB.NG_NHANCHUC
FROM DEAN DA JOIN PHONGBAN PB ON DA.PHONG = PB.MAPHG JOIN NHANVIEN NV ON PB.TRPHG = NV.MANV
WHERE DA.DDIEM_DA = 'HA NOI'

